<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpenseManager.Api.Repository\ExpenseManager.Api.Repository.csproj" />
    <ProjectReference Include="..\ExpenseManager.Shared\ExpenseManager.Shared.csproj" />
  </ItemGroup>

</Project>
